### ISSUE TITLE
StackOverflowError on PathFinderImpl.findPath

### ISSUE THREAD

**Issue by SomeFire** [b3dgs/warcraft-remake#18]
## Expected Behavior
Endpoint of path should be targeted at closest position to the clicked point.

## Actual Behavior
In some cases if path is blocked  - SOE happens.

## Steps to Reproduce the Problem
See [screenshot](https://pp.userapi.com/c850016/v850016720/1e32df/DB1kkrEcE08.jpg):

1. Move 1 unit to the forest corner.
2. Move second unit to near position.
3. Try to move second unit to the corner (where cursor on screenshot).

## Specifications

  - Warcraft Remake Version: 0.0.3-SNAPSHOT (19.07.2019)
  - JDK: 1.8_181
  - OS: Win10

**Comment by SomeFire** [comment]
```
java.lang.StackOverflowError
	at com.b3dgs.lionengine.game.feature.tile.map.pathfinding.MapTilePathModel.isTileNotAvailable(MapTilePathModel.java:88)
	at com.b3dgs.lionengine.game.feature.tile.map.pathfinding.MapTilePathModel.isAreaAvailable(MapTilePathModel.java:408)
	at com.b3dgs.lionengine.game.feature.tile.map.pathfinding.MapTilePathModel.getClosestAvailableTile(MapTilePathModel.java:180)
	at com.b3dgs.lionengine.game.feature.tile.map.pathfinding.MapTilePathModel.getClosestAvailableTile(MapTilePathModel.java:398)
	at com.b3dgs.lionengine.game.feature.tile.map.pathfinding.PathFinderImpl.findPath(PathFinderImpl.java:255)
```
