### ISSUE TITLE
Game crashes on wood extracting

### ISSUE THREAD

**Issue by SomeFire** [b3dgs/warcraft-remake#31]
## Expected Behavior
Peon gather wood.

## Actual Behavior
Game crashes.

## Steps to Reproduce the Problem

Order peon to extract wood.

## Specifications

  - Warcraft Remake Version: 0.0.4
  - JDK: 1.8
  - OS: Win10

**Comment by SomeFire** [comment]
```
com.b3dgs.lionengine.LionEngineException: Feature already exists: class com.b3dgs.lionengine.game.feature.tile.map.pathfinding.TilePathModel with: class com.b3dgs.lionengine.game.feature.tile.map.pathfinding.TilePathModel
	at com.b3dgs.lionengine.game.feature.Features.add(Features.java:92)
	at com.b3dgs.lionengine.game.feature.FeaturableModel.addFeature(FeaturableModel.java:182)
	at com.b3dgs.lionengine.game.feature.tile.map.pathfinding.MapTilePathModel.loadPathfinding(MapTilePathModel.java:270)
	at com.b3dgs.warcraft.object.State$4.notifyStartCarry(State.java:178)
	at com.b3dgs.lionengine.game.feature.tile.map.extractable.ExtractorModel.extract(ExtractorModel.java:197)
	at com.b3dgs.lionengine.game.feature.tile.map.extractable.ExtractorModel.actionExtracting(ExtractorModel.java:132)
	at com.b3dgs.lionengine.game.feature.tile.map.extractable.ExtractorModel.update(ExtractorModel.java:264)
	at com.b3dgs.warcraft.object.EntityUpdater.update(EntityUpdater.java:93)
	at com.b3dgs.lionengine.game.feature.ComponentRefreshable.update(ComponentRefreshable.java:115)
	at com.b3dgs.lionengine.game.feature.Handler.update(Handler.java:256)
	at com.b3dgs.lionengine.game.feature.WorldGame.update(WorldGame.java:228)
	at com.b3dgs.warcraft.World.update(World.java:192)
	at com.b3dgs.lionengine.game.feature.SequenceGame.update(SequenceGame.java:142)
	at com.b3dgs.lionengine.graphic.engine.Sequence$1.update(Sequence.java:227)
	at com.b3dgs.lionengine.graphic.engine.LoopFrameSkipping.start(LoopFrameSkipping.java:100)
	at com.b3dgs.lionengine.graphic.engine.Sequence.start(Sequence.java:222)
	at com.b3dgs.lionengine.graphic.engine.Loader.handle(Loader.java:100)
	at com.b3dgs.lionengine.graphic.engine.Loader.lambda$start$0(Loader.java:62)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by DjThunder** [comment]
Yes, already fixed, but a commit and deploy is missing on LionEngine 9.0.2-SNAPSHOT, in progress.
